using System;
using System.Text;
using ConfigRemedy.Core;
using ConfigRemedy.Domain;
using ConfigRemedy.Repository;
using ConfigRemedy.Repository.Infrastructure;
using ConfigRemedy.Security;
using Nancy.Cryptography;

namespace ConfigRemedy.NewApiKey
{
    class Program
    {
        static void Main(string[] args)
        {
            PrintHeader();

            using (var documentStore = RavenFactory.Create())
            {
                using (var session = documentStore.OpenSession())
                {
                    var apiKeyRepository = new ApiKeyRepository(session);
                    var apiKeyGenerator = new ApiKeyProvider(new RandomKeyGenerator());
                    var hashProvider = new HashedValueProvider();

                    var newKey = apiKeyGenerator.GenerateApiKey();

                    var apiKey = new ApiKey
                    {
                        Created = DateTime.UtcNow,
                        Usage = "Generated by new-apikey tool.",
                        HashedValue = hashProvider.GetHash(newKey),
                        UserId = "users/" + Constants.DefaultAdminUsername
                    };

                    apiKeyRepository.Store(apiKey);
                    PrintApiKey(newKey);
                }
            }
        }

        private static void PrintApiKey(string apiKey)
        {
            ConsoleColor currentForeground = Console.ForegroundColor;
            Console.WriteLine("New API key for user " + Constants.DefaultAdminUsername  + " is: ");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine(apiKey);
            Console.ForegroundColor = currentForeground;
            Console.WriteLine();
            Console.WriteLine("API keys cannot be retrieved from the once they're created. Generate a new key if you need another.");
            Console.WriteLine();
            Console.WriteLine();
        }
        private static void PrintHeader()
        {
            var sb = new StringBuilder();
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine("New API key generator utility");
            sb.AppendLine("------------------------------");

            Console.WriteLine(sb.ToString());
        }
    }
}
